#!/usr/bin/env python3
"""Generate the Kokoro phoneme table as Swift, from the engine's own config.

    Scripts/generate-vocab.py [path/to/kokoro_onnx/config.json]

The table maps phoneme symbols to the numbers the model is fed. Get one wrong
and nothing fails: the model speaks a different sound, confidently, and the
result is fluent English that is subtly not what was written. That is the worst
kind of bug to carry, because there is no error to notice and no line to blame.

So it is not copied by hand. This reads the table out of the installed engine
and writes the Swift, which removes transcription from the process entirely --
a generated file cannot have a typo in entry 47.

The source hash is embedded in the output. If the engine is upgraded and its
table changes, the checked-in Swift no longer matches and the test says so,
rather than the voice quietly drifting.

The reference setup this reads from was deleted on 2026-09-03, once nib had
replaced it. Everything it produced is committed under Tests/Fixtures, so the
tests do not need it -- but regenerating a fixture does. To rebuild it:

    python3.12 -m venv /tmp/kokoro-venv
    /tmp/kokoro-venv/bin/pip install kokoro-onnx phonemizer espeakng-loader \
        onnxruntime==1.29.0 numpy soundfile
    # models from https://github.com/thewh1teagle/kokoro-onnx/releases
    #   model-files-v1.0/kokoro-v1.0.onnx and voices-v1.0.bin

Then run this with that interpreter, passing the model directory where a path
is taken. Pin onnxruntime to 1.29.0: the audio fixture is compared bit for bit
and another build produces different samples.
"""

import hashlib
import json
import sys
from pathlib import Path

DEFAULT_SOURCE = Path.home() / (
    "code/per/voice-server-cloudci/vendor/kokoro-venv/lib/python3.12"
    "/site-packages/kokoro_onnx/config.json"
)
OUTPUT = Path(__file__).resolve().parent.parent / "Sources/nib/Speech/KokoroVocab.swift"


def swift_literal(text: str) -> str:
    """Swift string literal for a phoneme, which may be any Unicode symbol."""
    escaped = text.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def main() -> int:
    source = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_SOURCE
    if not source.exists():
        print(f"no config.json at {source}", file=sys.stderr)
        print("pass the path to kokoro_onnx/config.json", file=sys.stderr)
        return 1

    raw = source.read_bytes()
    digest = hashlib.sha256(raw).hexdigest()
    config = json.loads(raw)
    vocab: dict[str, int] = config["vocab"]

    # Sorted by the id rather than the symbol, so the generated file reads as
    # the model's own ordering and a diff between engine versions is legible.
    entries = sorted(vocab.items(), key=lambda pair: pair[1])
    rows = "\n".join(
        f"        {swift_literal(symbol)}: {number}," for symbol, number in entries
    )

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(f'''// Generated by Scripts/generate-vocab.py. Do not edit.
//
// The phoneme table Kokoro was trained with: each sound symbol and the number
// the model expects for it. Generated rather than transcribed, because a
// mistyped id does not fail -- it speaks a different sound, fluently, and
// nobody notices for weeks.
//
// Regenerate with:  Scripts/generate-vocab.py
enum KokoroVocab {{
    /// sha256 of the config.json this came from. The test compares it against
    /// the installed engine so an upgrade cannot silently change the voice.
    static let sourceDigest = "{digest}"

    /// Longest phoneme sequence the model accepts. Anything past this is cut.
    ///
    /// From MAX_PHONEME_LENGTH in kokoro_onnx/config.py, which is a constant in
    /// the source rather than a field in config.json -- so it is stated here
    /// rather than read, and the test checks it against the installed engine.
    static let maxPhonemes = 510

    static let table: [String: Int] = [
{rows}
    ]
}}
''', encoding="utf-8")

    print(f"wrote {OUTPUT.relative_to(OUTPUT.parent.parent.parent)}")
    print(f"  {len(entries)} phonemes, ids {entries[0][1]} to {entries[-1][1]}")
    print(f"  sha256 {digest[:16]}…")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
